### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by mundschenk-at** [ahebrank/squeezebox-utils#2]
Would you mind adding an explicit license of some kind? I'd like to adapt the approach of the watchpower.py script for use with piCorePlayer and I'd rather work from your code than do a reimplementation from scratch.

**Comment by ahebrank** [comment]
Sure, I can add an MIT license -- my only reservation is I can't remember where the idea for subscribing to the server control socket for "subscribe power" came from and/or I borrowed some of that code from a gist or something posted on a forum. 

I can't find anything from a quick search, though -- have you seen anything like that around? I'd like to credit in the script before it's propagated further, if I did appropriate that.

**Comment by mundschenk-at** [comment]
Thanks. I think it is the standard Squeezebox way to do stuff like that. Something similar was [suggested to me independently](https://forums.slimdevices.com/showthread.php?105117-lirc-rpi-gpio-IR-support-for-picoreplayer&p=940665&viewfull=1#post940665) of your implementation by the piCorePlayer developers. 

Anyway, I'm probably going to rewrite things from scratch (with credit for your script of course), because I'd also like some config file parsing and the differences between Python 2.x and µPython add up.

**Comment by ahebrank** [comment]
Sounds good -- good luck.
